# Generated by Django 2.2.6 on 2019-10-31 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('symbol', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now=True)),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Ticker')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('time_added', models.DateTimeField(auto_now=True)),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Ticker')),
            ],
        ),
        migrations.CreateModel(
            name='IntradayStockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('high', models.DecimalField(decimal_places=2, max_digits=16)),
                ('low', models.DecimalField(decimal_places=2, max_digits=16)),
                ('volume', models.IntegerField()),
                ('time_added', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Ticker')),
            ],
            options={
                'unique_together': {('symbol', 'time')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalStockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('high', models.DecimalField(decimal_places=2, max_digits=16)),
                ('low', models.DecimalField(decimal_places=2, max_digits=16)),
                ('volume', models.IntegerField()),
                ('time_added', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Ticker')),
            ],
            options={
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
