# Generated by Django 2.2.6 on 2019-10-31 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.Ticker')),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('high', models.DecimalField(decimal_places=2, max_digits=16)),
                ('low', models.DecimalField(decimal_places=2, max_digits=16)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('volume', models.IntegerField()),
                ('last_trading_day', models.DateField()),
                ('previous_close', models.DecimalField(decimal_places=2, max_digits=16)),
                ('time_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
